name: Comment By Label In Issues and PRs

on:
  issues:
    types: [labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  add-comment:
    if: contains(github.event.label.name, 'Help Wanted')
    runs-on: ubuntu-latest

    steps:
      - name: Add comment
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue comment "$ISSUE_NUMBER" --body \
          "This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:"
